AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-trading-system SAM stack
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  DDBTableName:
    Type: String
    Default: TradesStore
  TopicName:
    Type: String
    Default: OrdersDispatcherTopic

Resources:
  DataExtractorAPIDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Name: DataExtractorAPI
  SmartOrderRouterAPIDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Name: SmartOrderRouterAPI

  DDBTable:
    Type: AWS::DynamoDB::Table
    #DeletionPolicy: Retain
    Properties:
      TableName: !Ref DDBTableName
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  
  DDBStreamProcessingLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: TradesDataAggregator_sam
      CodeUri: aws/src/lambdas/tradesDataAggregator/
      Handler: tradesDataAggregator.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
      # Read more about SAM policy templates here
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaDynamoDBExecutionRole
        - DynamoDBWritePolicy: 
            TableName: !Ref DDBTable
      Environment:
        Variables:
          ddbTableName: !Ref DDBTable
      Architectures:
        - x86_64
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DDBTable.StreamArn
            BatchSize: 100
            StartingPosition: LATEST
  DataExtractorLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DataExtractor_sam
      CodeUri: aws/src/lambdas/dataExtractor/
      Handler: dataExtractor.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - DynamoDBReadPolicy: 
            TableName: !Ref DDBTable
      Environment:
        Variables:
          ddbTableName: !Ref DDBTable
      Architectures:
        - x86_64
      Events:
        DataExtractorAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref DataExtractorAPIDeployment
  SmartOrderRouterLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SmartOrderRouter_sam
      CodeUri: aws/src/lambdas/smartOrderRouter/
      Handler: smartOrderRouter.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - DynamoDBReadPolicy: 
            TableName: !Ref DDBTable
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
      Environment:
        Variables:
          ddbTableName: !Ref DDBTable
          ordersDispatcherTopicArn: !Ref OrdersDispatcherTopic
      Architectures:
        - x86_64
      Events:
        SmartOrderRouterAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref SmartOrderRouterAPIDeployment
  LitPoolMatchingEngineLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LitPoolMatchingEngine_sam
      CodeUri: aws/src/lambdas/litPoolMatchingEngine/
      Handler: litPoolMatchingEngine.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
      Architectures:
        - x86_64
  DarkPoolMatchingEngineLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DarkPoolMatchingEngine_sam
      CodeUri: aws/src/lambdas/darkPoolMatchingEngine/
      Handler: darkPoolMatchingEngine.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
      Architectures:
        - x86_64
  AvailableFundsRaiserLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AvailableFundsRaiser_sam
      CodeUri: aws/src/lambdas/availableFundsRaiser/
      Handler: availableFundsRaiser.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
        - DynamoDBWritePolicy: 
            TableName: !Ref DDBTable
      Environment:
        Variables:
          ddbTableName: !Ref DDBTable
      Architectures:
        - x86_64
  PostTradeProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostTradeProcessor_sam
      CodeUri: aws/src/lambdas/postTradeProcessor/
      Handler: postTradeProcessor.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
        - DynamoDBWritePolicy: 
            TableName: !Ref DDBTable
      Environment:
        Variables:
          ddbTableName: !Ref DDBTable
      Architectures:
        - x86_64
        
  OrdersDispatcherTopic:
   Type: AWS::SNS::Topic
   Properties:
     TopicName: !Ref TopicName

  OrdersDispatcherTopicLitPoolMatchingEngineLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt LitPoolMatchingEngineLambda.Arn
      Protocol: lambda
      TopicArn: !Ref OrdersDispatcherTopic
      FilterPolicy:
        PoolType:
          - Lit
  OrdersDispatcherTopicDarkPoolMatchingEngineLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt DarkPoolMatchingEngineLambda.Arn
      Protocol: lambda
      TopicArn: !Ref OrdersDispatcherTopic
      FilterPolicy:
        PoolType:
          - Dark
  OrdersDispatcherTopicAvailableFundsRaiserLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt AvailableFundsRaiserLambda.Arn
      Protocol: lambda
      TopicArn: !Ref OrdersDispatcherTopic
      FilterPolicy:
        InvalidOrders:
          - CreditCheck
  OrdersDispatcherTopicPostTradeProcessorLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt PostTradeProcessorLambda.Arn
      Protocol: lambda
      TopicArn: !Ref OrdersDispatcherTopic
      FilterPolicy:
        PostTrade:
          - "True"
  # Provide permission for SNS to invoke the Lambda function
  LitPoolMatchingEngineLambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref LitPoolMatchingEngineLambda
      Principal: sns.amazonaws.com
  DarkPoolMatchingEngineLambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref DarkPoolMatchingEngineLambda
      Principal: sns.amazonaws.com
  AvailableFundsRaiserLambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref AvailableFundsRaiserLambda
      Principal: sns.amazonaws.com
  PostTradeProcessorLambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref PostTradeProcessorLambda
      Principal: sns.amazonaws.com

  SamTradingSystemLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: sam-trading-system-lambda-layer
            Description: Dependencies for sam-trading-system
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs14.x
            CompatibleArchitectures:
              - x86_64
            RetentionPolicy: Retain

Outputs:
  OrdersDispatcherTopicARN:
    Description: OrdersDispatcherTopic ARN
    Value: !Ref OrdersDispatcherTopic