AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-trading-system SAM stack
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  tradesStoreTableName:
    Type: String
    Default: TradesStore
  MarketDataTableName:
    Type: String
    Default: MarketData
  TopicName:
    Type: String
    Default: OrdersDispatcherTopic
  TradesStorageS3BucketName:
    Type: String
    Default: serverless-trades-storage
  MarketDataS3BucketName:
    Type: String
    Default: serverless-market-data
  EventBusName:
    Type: String
    Default: trading-system-event-bus
  FargateMarketDataServicesBaseURL:
    Type: String
    Default: xxx

Resources:
  BusType:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /trading-system/dev/bus-type
      Type: String
      Value: EVENT-BRIDGE
      Description: SNS or EVENT-BRIDGE
  DarkPoolTickersList:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /trading-system/dev/dark-pool-tickers-list
      Type: StringList
      Value: FB,AMD,AMZN,APPL,NVDA,MO,GOOG,F,T,VTI
      Description: Orders with these tickers get sent to Dark Pools.
  DarkPoolsList:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /trading-system/dev/dark-pools
      Type: StringList
      Value: INSTINET,POSIT,LIQUIDNET,CHI-X,CROSS-FINDER,SIGMA-X,GETCO
      Description: List of Dark Pools
  LitPoolsList:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /trading-system/dev/lit-pools
      Type: StringList
      Value: IEX,ISLAND,BATS,BAT.BYX,EDGX,EDGA,NASDAQ,NASDAQ.ARCA,EBS
      Description: List of Lit Pools
  MarketDataApiBaseURL:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /trading-system/dev/market-data-api-base-url
      Type: String
      Value: https://yfapi.net/v11/finance/
      Description: Market Data Api Base URL
  MarketDataApiKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /trading-system/dev/market-data-api-key
      Type: String
      Value: xxx
      Description: Market Data Api Key
  DataExtractorAPIDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Name: DataExtractorAPI
  SmartOrderRouterAPIDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Name: SmartOrderRouterAPI

  DDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: !Ref tradesStoreTableName
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  
  MarketDataTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: !Ref MarketDataTableName
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 12

  TradesStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TradesStorageS3BucketName
  MarketDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MarketDataS3BucketName
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref EventBusName
  OrdersDispatcherTopic:
   Type: AWS::SNS::Topic
   Properties:
     TopicName: !Ref TopicName
  TradesDataAggregatorLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: TradesDataAggregator
      CodeUri: aws/src/lambdas/tradesDataAggregator/
      Handler: tradesDataAggregator.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
      # Read more about SAM policy templates here
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaDynamoDBExecutionRole
        - DynamoDBWritePolicy: 
            TableName: !Ref DDBTable
      Environment:
        Variables:
          tradesStoreTableName: !Ref DDBTable
      Architectures:
        - x86_64
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DDBTable.StreamArn
            BatchSize: 100
            StartingPosition: LATEST
  DataExtractorLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DataExtractor
      CodeUri: aws/src/lambdas/dataExtractor/
      Handler: dataExtractor.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - DynamoDBReadPolicy: 
            TableName: !Ref DDBTable
      Environment:
        Variables:
          tradesStoreTableName: !Ref DDBTable
      Architectures:
        - x86_64
      Events:
        DataExtractorAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref DataExtractorAPIDeployment
  SmartOrderRouterLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SmartOrderRouter
      CodeUri: aws/src/lambdas/smartOrderRouter/
      Handler: smartOrderRouter.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref DDBTable
        - DynamoDBReadPolicy:
            TableName: !Ref MarketDataTable
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref EventBusName
      Environment:
        Variables:
          tradesStoreTableName: !Ref DDBTable
          marketDataTableName: !Ref MarketDataTable
          ordersDispatcherTopicArn: !Ref OrdersDispatcherTopic
          eventBusName: !Ref EventBusName
      Architectures:
        - x86_64
      Events:
        SmartOrderRouterAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref SmartOrderRouterAPIDeployment
  LitPoolMatchingEngineLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LitPoolMatchingEngine
      CodeUri: aws/src/lambdas/litPoolMatchingEngine/
      Handler: litPoolMatchingEngine.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref EventBusName
      Environment:
        Variables:
          eventBusName: !Ref EventBus
          fargateMarketDataServicesBaseURL: !Ref FargateMarketDataServicesBaseURL
      Architectures:
        - x86_64
  DarkPoolMatchingEngineLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DarkPoolMatchingEngine
      CodeUri: aws/src/lambdas/darkPoolMatchingEngine/
      Handler: darkPoolMatchingEngine.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref EventBusName
      Environment:
        Variables:
          eventBusName: !Ref EventBus
          fargateMarketDataServicesBaseURL: !Ref FargateMarketDataServicesBaseURL
      Architectures:
        - x86_64
  AvailableFundsRaiserLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AvailableFundsRaiser
      CodeUri: aws/src/lambdas/availableFundsRaiser/
      Handler: availableFundsRaiser.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies: 
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
        - DynamoDBWritePolicy: 
            TableName: !Ref DDBTable
      Environment:
        Variables:
          tradesStoreTableName: !Ref DDBTable
      Architectures:
        - x86_64
  PostTradeProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostTradeProcessor
      CodeUri: aws/src/lambdas/postTradeProcessor/
      Handler: postTradeProcessor.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies:
        - S3WritePolicy:
            BucketName: !Ref TradesStorageS3BucketName
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
        - DynamoDBWritePolicy: 
            TableName: !Ref DDBTable
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref EventBusName
      Environment:
        Variables:
          tradesStoreTableName: !Ref DDBTable
          bucketName: !Ref TradesStorageS3BucketName
          eventBusName: !Ref EventBus
      Architectures:
        - x86_64
  TradesStorageAnalyzerLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: TradesStorageAnalyzer
      CodeUri: aws/dist/lambdas/tradesStorageAnalyzer/
      Handler: tradesStorageAnalyzer.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref TradesStorageS3BucketName
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref TradesStorageBucket
            Events: s3:ObjectCreated:*
      Architectures:
        - x86_64
  
  MarketDataManagerLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MarketDataManager
      CodeUri: aws/dist/lambdas/marketDataManager/
      Handler: marketDataManager.handler
      Layers:
        - !Ref SamTradingSystemLayer
      Runtime: nodejs14.x
      Policies:
        - S3WritePolicy:
            BucketName: !Ref MarketDataBucket
        - SSMParameterReadPolicy:
            ParameterName: "*"
        - DynamoDBWritePolicy: 
            TableName: !Ref MarketDataTable
      Environment:
        Variables:
          bucketName: !Ref MarketDataS3BucketName
          eventBusName: !Ref EventBus
          marketDataTableName: !Ref MarketDataTable
      Architectures:
        - x86_64

  SamTradingSystemLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: sam-trading-system-lambda-layer
            Description: Dependencies for sam-trading-system
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs14.x
            CompatibleArchitectures:
              - x86_64
            RetentionPolicy: Retain
  
  OrdersDispatcherTopicLitPoolMatchingEngineLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt LitPoolMatchingEngineLambda.Arn
      Protocol: lambda
      TopicArn: !Ref OrdersDispatcherTopic
      FilterPolicy:
        PoolType:
          - Lit
  OrdersDispatcherTopicDarkPoolMatchingEngineLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt DarkPoolMatchingEngineLambda.Arn
      Protocol: lambda
      TopicArn: !Ref OrdersDispatcherTopic
      FilterPolicy:
        PoolType:
          - Dark
  OrdersDispatcherTopicAvailableFundsRaiserLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt AvailableFundsRaiserLambda.Arn
      Protocol: lambda
      TopicArn: !Ref OrdersDispatcherTopic
      FilterPolicy:
        InvalidOrders:
          - CreditCheck
  OrdersDispatcherTopicPostTradeProcessorLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt PostTradeProcessorLambda.Arn
      Protocol: lambda
      TopicArn: !Ref OrdersDispatcherTopic
      FilterPolicy:
        PostTrade:
          - "True"

  LitPoolsOrdersRule:
    Type: AWS::Events::Rule
    Properties:
      Name: LitPoolsOrders
      Description: Forward orders coming from SmartOrderRouter or DarkPoolMatchingEngine to LitPoolMatchingEngine.
      EventBusName: !Ref EventBus
      EventPattern: 
        source: 
          - "SmartOrderRouter"
          - "DarkPoolMatchingEngine"
        detail-type:
          - Orders
        detail: 
          PoolType: 
            - "Lit"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "LitPoolMatchingEngineLambda"
              - "Arn"
          Id: "LitPoolMatchingEngineTarget"
          InputPath: "$.detail.Orders"
  DarkPoolsOrdersRule:
    Type: AWS::Events::Rule
    Properties:
      Name: DarkPoolsOrders
      Description: Forward orders coming from SmartOrderRouter to DarkPoolMatchingEngine.
      EventBusName: !Ref EventBus
      EventPattern: 
        source: 
          - "SmartOrderRouter"
        detail-type:
          - Orders
        detail: 
          PoolType: 
            - "Dark"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "DarkPoolMatchingEngineLambda"
              - "Arn"
          Id: "DarkPoolMatchingEngineTarget"
          InputPath: "$.detail.Orders"
  AvailableFundsRaiserRule:
    Type: AWS::Events::Rule
    Properties:
      Name: AvailableFundsRaiser
      Description: Forward SmartOrderRouter orders with customers credit check failed to AvailableFundsRaiser.
      EventBusName: !Ref EventBus
      EventPattern: 
        source: 
          - "SmartOrderRouter"
        detail-type:
          - Orders
        detail: 
          InvalidOrders: 
            - "CreditCheck"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "AvailableFundsRaiserLambda"
              - "Arn"
          Id: "AvailableFundsRaiserTarget"
          InputPath: "$.detail.Orders"
  PostTradeProcessorRule:
    Type: AWS::Events::Rule
    Properties:
      Name: PostTradeProcessor
      Description: Post processes trades coming from Dark or Lit pool matching engines.
      EventBusName: !Ref EventBus
      EventPattern: 
        source: 
          - "LitPoolMatchingEngine"
          - "DarkPoolMatchingEngine"
        detail-type:
          - Trades
        detail: 
          PostTrade: 
            - "True"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "PostTradeProcessorLambda"
              - "Arn"
          Id: "PostTradeProcessorTarget"
          InputPath: "$.detail.Trades"
  MarketDataManagerRule:
    Type: AWS::Events::Rule
    Properties:
      Name: MarketDataManager
      Description: Receives market data requests, call the market data provider and store the outcome in DynamoDB and S3.
      EventBusName: !Ref EventBus
      EventPattern: 
        source: 
          - "SmartOrderRouter"
        detail-type:
          - MarketData
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "MarketDataManagerLambda"
              - "Arn"
          Id: "MarketDataManagerTarget"

  # Provide permission for EventBridre to invoke the Lambda function
  LitPoolMatchingEngineLambdaEventsInvokePermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "LitPoolMatchingEngineLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "LitPoolsOrdersRule"
          - "Arn"
  DarkPoolMatchingEngineLambdaEventsInvokePermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "DarkPoolMatchingEngineLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "DarkPoolsOrdersRule"
          - "Arn"
  AvailableFundsRaiserLambdaEventsInvokePermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "AvailableFundsRaiserLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "AvailableFundsRaiserRule"
          - "Arn"
  PostTradeProcessorLambdaEventsInvokePermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "PostTradeProcessorLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "PostTradeProcessorRule"
          - "Arn"
  MarketDataManagerLambdaEventsInvokePermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "MarketDataManagerLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "MarketDataManagerRule"
          - "Arn"
      
  # Provide permission for SNS to invoke the Lambda function
  LitPoolMatchingEngineLambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref LitPoolMatchingEngineLambda
      Principal: sns.amazonaws.com
  DarkPoolMatchingEngineLambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref DarkPoolMatchingEngineLambda
      Principal: sns.amazonaws.com
  AvailableFundsRaiserLambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref AvailableFundsRaiserLambda
      Principal: sns.amazonaws.com
  PostTradeProcessorLambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref PostTradeProcessorLambda
      Principal: sns.amazonaws.com

Outputs:
  OrdersDispatcherTopicARN:
    Description: OrdersDispatcherTopic ARN
    Value: !Ref OrdersDispatcherTopic
  TradesStorageBucketInfo:
    Value: !Ref TradesStorageBucket
    Description: S3 Bucket for trades storage
  SmartOrderRouterAPIDeploymentInfo:
    Value: !Ref SmartOrderRouterAPIDeployment
    Description: Smart Order Router API Deployment
  EventBusInfo:
    Value: !Ref EventBus
    Description: Event Bus